-- AlterTable
ALTER TABLE "Breakdown" ALTER COLUMN "beginAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "takenAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Intervention" ALTER COLUMN "beginAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Maintenance" ALTER COLUMN "beginAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "phoneAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "safetyAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "wiresAt" SET DATA TYPE TIMESTAMP(3);
